services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    build: .
    container_name: springboot-app
    restart: always
    environment:
      DB_USERNAME: root
      DB_PASSWORD: admin
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: test
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
